package com.harness.core.model;

import java.util.List;

/**
 * Root structure of {@code project-apis.json} (§4.1 of TODO5).
 *
 * @param discoveredAt      ISO-8601 timestamp of when the scan was performed
 * @param projectDescription project description (generated by AI or manually set)
 * @param baseUrl           global base URL for all endpoints (e.g. "http://localhost:8081")
 * @param projectRoot       absolute path to the local project root directory
 * @param endpoints         list of discovered API endpoint declarations
 */
public record ProjectApiConfig(
        String discoveredAt,
        String projectDescription,
        String baseUrl,
        String projectRoot,
        List<ApiEndpoint> endpoints
) {
    public ProjectApiConfig {
        if (endpoints == null) endpoints = List.of();
    }

    /**
     * Resolve the effective base URL for an endpoint.
     * Endpoint-level baseUrl overrides global baseUrl.
     */
    public String resolveBaseUrl(ApiEndpoint endpoint) {
        if (endpoint.baseUrl() != null && !endpoint.baseUrl().isBlank()) {
            return endpoint.baseUrl();
        }
        return baseUrl != null ? baseUrl : "";
    }

    /**
     * Return a new config with the given endpoints list (immutable copy).
     */
    public ProjectApiConfig withEndpoints(List<ApiEndpoint> newEndpoints) {
        return new ProjectApiConfig(discoveredAt, projectDescription, baseUrl, projectRoot, newEndpoints);
    }
}
